ansible_connection: local

casks:
  - homebrew/cask-fonts
  - d12frosted/emacs-plus

packages:
  - go
  - yarn
  - node
  - fish
  - git
  - tmux
  - neovim
  - rust
  - openssh
  - openssl
  - emacs-plus
  - htop
  - ansible-lint
  - vim
  - editorconfig
  - zsh
  - svn

cask_packages:
  - iterm2
  - postman
  - visual-studio-code
  - tower
  - firefox
  - dingtalk
  - wechat
  - thunder
  - v2rayu
  - squidman
  - notion
  - qqmusic
  - docker
  - dozer
  - moom
  - pock
  - telegram
  - qq
  - mounty
  - macvim
  - virtualbox
  - balenaetcher
  - hyper
  - aliwangwang
  - baidunetdisk
  - 1password
  - google-chrome
  - the-unarchiver
  - font-ubuntu-mono

yarn_packages:
  - prettier
  - eslint
  - nodemon
  - serve
  - pm2
  - typescript
  - semantic-release
  - create-react-app

dotfiles_base_path: "{{ playbook_dir }}/stuff/dotfiles"

templates:
  - src: "{{ dotfiles_base_path }}/.gitconfig.j2"
    dest: "~/.gitconfig"

  - src: "{{ dotfiles_base_path }}/.profile.j2"
    dest: ~/.profile

  - src: "{{ dotfiles_base_path }}/config.fish.j2"
    dest: ~/.config/fish/config.fish

  - src: "{{ dotfiles_base_path }}/.tmux.conf.local.j2"
    dest: ~/.tmux.conf.local

  - src: "{{ dotfiles_base_path }}/.zshrc.j2"
    dest: ~/.zshrc
